### ISSUE TITLE
setting environmental variable for google api key

### ISSUE THREAD

**Issue by NewGraphEnvironment** [NewGraphEnvironment/safety_plan_elk_2022#1]
@mateo9569 created an api key but needs to add it as an environmental variable

**Comment by NewGraphEnvironment** [comment]
`usethis::edit_r_environ()`

**Comment by Mateo9569** [comment]
I did that already, but now I'm getting this error:

![image](https://user-images.githubusercontent.com/99455166/191363202-e6555ced-e04a-403d-a04a-cf389ca8ccf2.png)

**Comment by NewGraphEnvironment** [comment]
perhaps your project does not include the `Maps Embed API` in its allowed apis?   googling the error "google maps platform rejected your request. the api project is not authorized to use this api" results in this hit.  Maybe give it a shot and send a screenshot of the settings for the key you grabbed if you can't get it to work.

https://www.deviodigital.com/articles/how-to-fix-the-google-maps-platform-rejected-your-request-error/#:~:text=%E2%80%9CGoogle%20Maps%20Platform%20rejected%20your%20request.,map%20like%20it's%20supposed%20to.

**Comment by Mateo9569** [comment]
Ok, I finally got it to work. Google maps platform is hard to navigate especially when you've never used it. There's a lot going on.
